apiVersion: v1
data:
  username: cm9vdA==
  password: ZXhhbXBsZQ==
  mongo_url: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBsb2NhbGhvc3Q6MjcwMTcvbWV1QmFuY28/YXV0aFNvdXJjZT1hZG1pbg==
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: mongo-creds