apiVersion: v1
kind: Service
metadata:
  name: app-nodeport-svc
  labels:
    app: app-lanchonete-fiap
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
  selector:
    app: app-lanchonete-fiap
status:
  loadBalancer: {}